### ISSUE TITLE
error when running -mails

### ISSUE THREAD

**Issue by Aaranaw** [alessiop86/ptc-registration#1]
Hi just testing this on my machine receiving the following error

root@Lilith:/opt/Pokemon/ptc-registration# python script.py -mails
Registration of account C54641A0EEA2:E78D852FCB - Start
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Registration of account C54641A0EEA2:E78D852FCB - failed
Traceback (most recent call last):
  File "script.py", line 44, in execute
    self.execute_first_call(session)
  File "script.py", line 67, in execute_first_call
    first_page = session.get(url1).text
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 487, in get
    return self.request('GET', url, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, *_send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 617, in send
    r.content
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 741, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 669, in generate
    raise ContentDecodingError(e)
ContentDecodingError: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing: incorrect header check',))
Registration of account 3268A573D494:3FEDA11841 - Start
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Registration of account 3268A573D494:3FEDA11841 - failed
Traceback (most recent call last):
  File "script.py", line 44, in execute
    self.execute_first_call(session)
  File "script.py", line 67, in execute_first_call
    first_page = session.get(url1).text
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 487, in get
    return self.request('GET', url, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, *_send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 617, in send
    r.content
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 741, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 667, in generate
    raise ChunkedEncodingError(e)
ChunkedEncodingError: ('Connection broken: IncompleteRead(54 bytes read)', IncompleteRead(54 bytes read))
Registration of account 96D68B8958C8:0CB4FA6FF9 - Start
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Registration of account 96D68B8958C8:0CB4FA6FF9 - failed
Traceback (most recent call last):
  File "script.py", line 44, in execute
    self.execute_first_call(session)
  File "script.py", line 67, in execute_first_call
    first_page = session.get(url1).text
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 487, in get
    return self.request('GET', url, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, *_send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 617, in send
    r.content
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 741, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 669, in generate
    raise ContentDecodingError(e)
ContentDecodingError: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing: incorrect header check',))
Registration of account 13AAE403C1A8:40CDF74586 - Start
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
^CRegistration of account 13AAE403C1A8:40CDF74586 - failed
Traceback (most recent call last):
  File "script.py", line 44, in execute
    self.execute_first_call(session)
  File "script.py", line 67, in execute_first_call
    first_page = session.get(url1).text
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 487, in get
    return self.request('GET', url, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, *_send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 606, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 108, in resolve_redirects
    resp.content  # Consume socket so it can be released
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 741, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 664, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/response.py", line 349, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/response.py", line 498, in read_chunked
    self._update_chunk_length()
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/response.py", line 444, in _update_chunk_length
    line = self._fp.fp.readline()
  File "/usr/lib/python2.7/socket.py", line 447, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib/python2.7/ssl.py", line 241, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 160, in read
    return self._sslobj.read(len)
KeyboardInterrupt
Registration of account 7B73FF8AF979:4898CC991B - Start
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Registration of account 7B73FF8AF979:4898CC991B - failed
Traceback (most recent call last):
  File "script.py", line 44, in execute
    self.execute_first_call(session)
  File "script.py", line 67, in execute_first_call
    first_page = session.get(url1).text
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 487, in get
    return self.request('GET', url, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, *_send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 606, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 179, in resolve_redirects
    **adapter_kwargs
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 617, in send
    r.content
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 741, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 669, in generate
    raise ContentDecodingError(e)
ContentDecodingError: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing: incorrect header check',))
Registration of account 155A10433276:286CC0640A - Start
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Registration of account 155A10433276:286CC0640A - failed
Traceback (most recent call last):
  File "script.py", line 44, in execute
    self.execute_first_call(session)
  File "script.py", line 68, in execute_first_call
    text_file = io.open(self.logfile1, "w", encoding='utf-8')
IOError: [Errno 2] No such file or directory: 'logs/page1.155A10433276.html'
Registration of account 520B9F14F096:BEF3050254 - Start
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Registration of account 520B9F14F096:BEF3050254 - failed
Traceback (most recent call last):
  File "script.py", line 44, in execute
    self.execute_first_call(session)
  File "script.py", line 68, in execute_first_call
    text_file = io.open(self.logfile1, "w", encoding='utf-8')
IOError: [Errno 2] No such file or directory: 'logs/page1.520B9F14F096.html'
Registration of account C8437F7F10F5:7A192D6F9D - Start
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Registration of account C8437F7F10F5:7A192D6F9D - failed
Traceback (most recent call last):
  File "script.py", line 44, in execute
    self.execute_first_call(session)
  File "script.py", line 68, in execute_first_call
    text_file = io.open(self.logfile1, "w", encoding='utf-8')
IOError: [Errno 2] No such file or directory: 'logs/page1.C8437F7F10F5.html'

**Comment by alessiop86** [comment]
Hi @Aaranaw , try this

`pip install 'requests[security]'`

What python version do you have? 2.7.what?

**Comment by Aaranaw** [comment]
Hi, that seems to have cleared the bulk of the errors however its still throwing the following

root@Lilith:/opt/Pokemon/ptc-registration# python script.py -mails
Registration of account CD37C327FCBD:62F426131D - Start
Registration of account CD37C327FCBD:62F426131D - failed
Traceback (most recent call last):
  File "script.py", line 44, in execute
    self.execute_first_call(session)
  File "script.py", line 68, in execute_first_call
    text_file = io.open(self.logfile1, "w", encoding='utf-8')
IOError: [Errno 2] No such file or directory: 'logs/page1.CD37C327FCBD.html'
Registration of account 38AB9D01EA3D:53E64B8CE7 - Start
Registration of account 38AB9D01EA3D:53E64B8CE7 - failed
Traceback (most recent call last):
  File "script.py", line 44, in execute
    self.execute_first_call(session)
  File "script.py", line 68, in execute_first_call
    text_file = io.open(self.logfile1, "w", encoding='utf-8')
IOError: [Errno 2] No such file or directory: 'logs/page1.38AB9D01EA3D.html'
Registration of account 1FE3B0AE92D1:A9E140A236 - Start
Registration of account 1FE3B0AE92D1:A9E140A236 - failed
Traceback (most recent call last):
  File "script.py", line 44, in execute
    self.execute_first_call(session)
  File "script.py", line 68, in execute_first_call
    text_file = io.open(self.logfile1, "w", encoding='utf-8')
IOError: [Errno 2] No such file or directory: 'logs/page1.1FE3B0AE92D1.html'
^CTraceback (most recent call last):
  File "script.py", line 158, in <module>
    main(sys.argv[1:])
  File "script.py", line 146, in main
    generate_from_email_list()
  File "script.py", line 131, in generate_from_email_list
    time.sleep(seconds_between_each_registration)
KeyboardInterrupt
root@Lilith:/opt/Pokemon/ptc-registration#

**Comment by alessiop86** [comment]
Create a "logs" folder (or checkout the updated version of the script, I inserted the logs folder now

**Comment by Aaranaw** [comment]
That worked great thanks, do you have any plans to implement email account creation (guerrilla mail?) and confirmation too? Thanks again.

**Comment by alessiop86** [comment]
No, it serves my purposes as it is. If someone wants to implement it I will accept external contributions and pull requests
